title: J3rich0 Terminal
email: j3rich0123@proton.me
description: CTF writeups, homelab experiments, and AD pentesting.

baseurl: "/cyberblog"
url: "https://j3r1ch0123.github.io"

github_username: j3r1ch0123

permalink: /writeups/:slug/

theme: jekyll-theme-midnight

plugins:
  - jekyll-feed

collections:
  writeups:
    output: true
    permalink: /writeups/:name/

# Exclude from processing
# exclude:
#   - Gemfile
#   - Gemfile.lock
